[build]
  base = "frontend"
  command = "yarn build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  YARN_VERSION = "1.22.19"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
